#!/usr/bin/env bash

allennlp train training_config/dream/dream.gpt.best.test.jsonnet -s tmp/dream.cross.base_human1 -j /checkpoint/siddk/debate/runs/dream/dream.bert_mc_gpt.bsz=32.lr=2.0e-05.f/model.tar.gz -e -d f -o "{'train_data_path': 'allennlp/tests/fixtures/data/dream/train.json', 'validation_data_path': 'datasets/dream/test_human1.json'}" 2>&1 | tee dream_base_human1.txt
allennlp train training_config/dream/dream.gpt.best.test.jsonnet -s tmp/dream.cross.base_human2 -j /checkpoint/siddk/debate/runs/dream/dream.bert_mc_gpt.bsz=32.lr=2.0e-05.f/model.tar.gz -e -d f -o "{'train_data_path': 'allennlp/tests/fixtures/data/dream/train.json', 'validation_data_path': 'datasets/dream/test_human2.json'}" 2>&1 | tee dream_base_human2.txt
allennlp train training_config/dream/dream.gpt.best.test.jsonnet -s tmp/dream.cross.base_human3 -j /checkpoint/siddk/debate/runs/dream/dream.bert_mc_gpt.bsz=32.lr=2.0e-05.f/model.tar.gz -e -d f -o "{'train_data_path': 'allennlp/tests/fixtures/data/dream/train.json', 'validation_data_path': 'datasets/dream/test_human3.json'}" 2>&1 | tee dream_base_human3.txt

allennlp train training_config/dream/dream.gpt.best.test.jsonnet -s tmp/dream.cross.base_tfidf_qa -j /checkpoint/siddk/debate/runs/dream/dream.bert_mc_gpt.bsz=32.lr=2.0e-05.f/model.tar.gz -e -d f -o "{'train_data_path': 'allennlp/tests/fixtures/data/dream/train.json', 'validation_data_path': 'datasets/dream/test_tfidf_qa.json'}" 2>&1 | tee dream_base_tf_idf_qa.txt
allennlp train training_config/dream/dream.gpt.best.test.jsonnet -s tmp/dream.cross.base_tfidf_a -j /checkpoint/siddk/debate/runs/dream/dream.bert_mc_gpt.bsz=32.lr=2.0e-05.f/model.tar.gz -e -d f -o "{'train_data_path': 'allennlp/tests/fixtures/data/dream/train.json', 'validation_data_path': 'datasets/dream/test_tfidf_a.json'}" 2>&1 | tee dream_base_tf_idf_a.txt
allennlp train training_config/dream/dream.gpt.best.test.jsonnet -s tmp/dream.cross.base_fasttext -j /checkpoint/siddk/debate/runs/dream/dream.bert_mc_gpt.bsz=32.lr=2.0e-05.f/model.tar.gz -e -d f -o "{'train_data_path': 'allennlp/tests/fixtures/data/dream/train.json', 'validation_data_path': 'datasets/dream/test_fasttext.json'}" 2>&1 | tee dream_base_fasttext.txt

allennlp train training_config/dream/dream.gpt.best.test.jsonnet -s tmp/dream.cross.base_base -j /checkpoint/siddk/debate/runs/dream/dream.bert_mc_gpt.bsz=32.lr=2.0e-05.f/model.tar.gz -e -d f -o "{'train_data_path': 'allennlp/tests/fixtures/data/dream/train.json', 'validation_data_path': 'datasets/dream/test_bert_base.json'}" 2>&1 | tee dream_base_base.txt
allennlp train training_config/dream/dream.gpt.best.test.jsonnet -s tmp/dream.cross.base_large -j /checkpoint/siddk/debate/runs/dream/dream.bert_mc_gpt.bsz=32.lr=2.0e-05.f/model.tar.gz -e -d f -o "{'train_data_path': 'allennlp/tests/fixtures/data/dream/train.json', 'validation_data_path': 'datasets/dream/test_bert_large.json'}" 2>&1 | tee dream_base_large.txt

allennlp train training_config/dream/dream.gpt.best.test.jsonnet -s tmp/dream.cross.base_sl -j /checkpoint/siddk/debate/runs/dream/dream.bert_mc_gpt.bsz=32.lr=2.0e-05.f/model.tar.gz -e -d f -o "{'train_data_path': 'allennlp/tests/fixtures/data/dream/train.json', 'validation_data_path': 'datasets/dream/test_sl.json'}" 2>&1 | tee dream_base_sl.txt
allennlp train training_config/dream/dream.gpt.best.test.jsonnet -s tmp/dream.cross.base_sl_sents -j /checkpoint/siddk/debate/runs/dream/dream.bert_mc_gpt.bsz=32.lr=2.0e-05.f/model.tar.gz -e -d f -o "{'train_data_path': 'allennlp/tests/fixtures/data/dream/train.json', 'validation_data_path': 'datasets/dream/test_sl_sents.json'}" 2>&1 | tee dream_base_sl_sents.txt
allennlp train training_config/dream/dream.gpt.best.test.jsonnet -s tmp/dream.cross.base_sl_sents_i -j /checkpoint/siddk/debate/runs/dream/dream.bert_mc_gpt.bsz=32.lr=2.0e-05.f/model.tar.gz -e -d f -o "{'train_data_path': 'allennlp/tests/fixtures/data/dream/train.json', 'validation_data_path': 'datasets/dream/test_sl_sents_i.json'}" 2>&1 | tee dream_base_sl_sents_i.txt

