#!/usr/bin/env bash

# TF-IDF QA
python baselines/tfidf.py -q -t datasets/race_raw/train -v eval/race/race.m=sl.best.e/test/ⅰ.json eval/race/race.m=sl.best.e/test/ⅱ.json eval/race/race.m=sl.best.e/test/ⅳ.json 2>&1 | tee tfidf_qa_sl.txt; python baselines/tfidf.py -q -t datasets/race_raw/train -v eval/race/race.m=sl-sents.best.e/test/ⅰ.json eval/race/race.m=sl-sents.best.e/test/ⅱ.json eval/race/race.m=sl-sents.best.e/test/ⅲ.json eval/race/race.m=sl-sents.best.e/test/ⅳ.json 2>&1 | tee tfidf_qa_sl_sents.txt; python baselines/tfidf.py -q -t datasets/race_raw/train -v eval/race/race.m=sl-sents.i.best.e/test/ⅰ.json eval/race/race.m=sl-sents.i.best.e/test/ⅱ.json eval/race/race.m=sl-sents.i.best.e/test/ⅲ.json eval/race/race.m=sl-sents.i.best.e/test/ⅳ.json 2>&1 | tee tfidf_qa_sl_sents_i.txt; python baselines/tfidf.py -t datasets/race_raw/train -v eval/race/race.m=sl.best.e/test/ⅰ.json eval/race/race.m=sl.best.e/test/ⅱ.json eval/race/race.m=sl.best.e/test/ⅳ.json 2>&1 | tee tfidf_a_sl.txt; python baselines/tfidf.py -t datasets/race_raw/train -v eval/race/race.m=sl-sents.best.e/test/ⅰ.json eval/race/race.m=sl-sents.best.e/test/ⅱ.json eval/race/race.m=sl-sents.best.e/test/ⅲ.json eval/race/race.m=sl-sents.best.e/test/ⅳ.json 2>&1 | tee tfidf_a_sl_sents.txt; python baselines/tfidf.py -t datasets/race_raw/train -v eval/race/race.m=sl-sents.i.best.e/test/ⅰ.json eval/race/race.m=sl-sents.i.best.e/test/ⅱ.json eval/race/race.m=sl-sents.i.best.e/test/ⅲ.json eval/race/race.m=sl-sents.i.best.e/test/ⅳ.json 2>&1 | tee tfidf_a_sl_sents_i.txt; python baselines/fasttext.py -v eval/race/race.m=sl.best.e/test/ⅰ.json eval/race/race.m=sl.best.e/test/ⅱ.json eval/race/race.m=sl.best.e/test/ⅳ.json 2>&1 | tee fasttext_sl.txt; python baselines/fasttext.py -v eval/race/race.m=sl-sents.best.e/test/ⅰ.json eval/race/race.m=sl-sents.best.e/test/ⅱ.json eval/race/race.m=sl-sents.best.e/test/ⅲ.json eval/race/race.m=sl-sents.best.e/test/ⅳ.json 2>&1 | tee fasttext_sl_sents.txt; python baselines/fasttext.py -v eval/race/race.m=sl-sents.i.best.e/test/ⅰ.json eval/race/race.m=sl-sents.i.best.e/test/ⅱ.json eval/race/race.m=sl-sents.i.best.e/test/ⅲ.json eval/race/race.m=sl-sents.i.best.e/test/ⅳ.json 2>&1 | tee fasttext_sl_sents_i.txt

# BERT
allennlp train race.best.last_epoch.f/config.json -s race.best.last_epoch.f -e -d f -o "{'train_data_path': 'allennlp/tests/fixtures/data/race_raw/train', 'validation_data_path': 'datasets/race_raw/test_sl'}" -r 2>&1 | tee cross_base_sl.txt; allennlp train race.best.last_epoch.f/config.json -s race.best.last_epoch.f -e -d f -o "{'train_data_path': 'allennlp/tests/fixtures/data/race_raw/train', 'validation_data_path': 'datasets/race_raw/test_sl_sents'}" -r 2>&1 | tee cross_base_sl_sents.txt; allennlp train race.best.last_epoch.f/config.json -s race.best.last_epoch.f -e -d f -o "{'train_data_path': 'allennlp/tests/fixtures/data/race_raw/train', 'validation_data_path': 'datasets/race_raw/test_sl_sents_i'}" -r 2>&1 | tee cross_base_sl_sents_i.txt; allennlp train training_config/race/race.large.best.jsonnet -s tmp/cross.large_sl -j /checkpoint/siddk/debate/runs/race/race.f.bert_mc_gpt.large.bsz=12.lr=5e-6.f/model.tar.gz -e -d f -o "{'train_data_path': 'allennlp/tests/fixtures/data/race_raw/train', 'validation_data_path': 'datasets/race_raw/test_sl'}" 2>&1 | tee cross_large_sl.txt; allennlp train training_config/race/race.large.best.jsonnet -s tmp/cross.large_sl_sents -j /checkpoint/siddk/debate/runs/race/race.f.bert_mc_gpt.large.bsz=12.lr=5e-6.f/model.tar.gz -e -d f -o "{'train_data_path': 'allennlp/tests/fixtures/data/race_raw/train', 'validation_data_path': 'datasets/race_raw/test_sl_sents'}" 2>&1 | tee cross_large_sl_sents.txt; allennlp train training_config/race/race.large.best.jsonnet -s tmp/cross.large_sl_sents_i -j /checkpoint/siddk/debate/runs/race/race.f.bert_mc_gpt.large.bsz=12.lr=5e-6.f/model.tar.gz -e -d f -o "{'train_data_path': 'allennlp/tests/fixtures/data/race_raw/train', 'validation_data_path': 'datasets/race_raw/test_sl_sents_i'}" 2>&1 | tee cross_large_sl_sents_i.txt


